### ISSUE TITLE
Fix TLS for CNAME-s

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/courier#4]
It would be nice to backport it to Jessie.

https://github.com/svarshavchik/courier-libs/commit/5e522ab14f45c6f4f43c43e32a2f72fbf6354f1c

**Comment by mwanner** [comment]
I've filed a Debian issue for this here: https://bugs.debian.org/860762, however, I don't think a backport to jessie is feasible.

**Comment by szepeviktor** [comment]
I've already backported it in a temporary VPS - the source is lost.
https://github.com/svarshavchik/courier-libs/commit/5e522ab14f45c6f4f43c43e32a2f72fbf6354f1c.patch

**Comment by szepeviktor** [comment]
...but I am using the package on some satellite servers.

**Comment by szepeviktor** [comment]
@mwanner Thanks.
